version: "3.9"

services:
  api:
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
    command: gunicorn --bind=0.0.0.0:8000 --workers=2 --threads=4 _project.wsgi
    env_file:
      - .env.aws
    labels:
      - traefik.http.routers.api.rule=Host(`${API_HOST}`)
      - traefik.http.services.api.loadbalancer.server.port=8000
      - traefik.http.routers.api.tls=true
  pwa:
    restart: always
    build:
      context: pwa
      dockerfile: Dockerfile.prod
    command: npm run start
    env_file:
      - .env.aws
    labels:
      - traefik.http.routers.pwa.rule=Host(`${FRONTEND_HOST}`)
      - traefik.http.services.pwa.loadbalancer.server.port=3000
      - traefik.http.routers.pwa.tls=true
    
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
    labels:
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.redirs.entrypoints=web
      - traefik.http.routers.redirs.middlewares=redirect-to-https
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro